server:
 port: 8072

spring:
  mail:
    host: smtp.gmail.com
    username: testbanchan7@gmail.com
    password: pghr glco gofj kzjk
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  application:
    name: practiceapi
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always

#  h2:
#    console:
#      enable: true;
#      path: /h2-console

#datasource:
  #url: jdbc:h2:mem:test
  #username: sa
  #password:
  #driver-class-name: org.h2.Driver // myoci
  datasource:
    url: jdbc:mariadb://localhost:3306/myblog
    username: root
    password: 12345
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    gcp:
      storage:
        credentials:
          location: classpath:gcs/imgstorage.json
        project-id: imgtest-429913
        bucket: imgtest_bucket

#pc 로컬 root/12345   myoci 오라클 무료 db test/1234

#resilience4j.ratelimeter
resilience4j.ratelimiter:
  instances:
    sign:
      limitForPeriod: 10
      limitRefreshPeriod: 1s
      timeoutDuration: 0






myblog:
  strKey: "qwerasdKDJFIEONqweriahsdfjasjdERRERqsfhgkop"
  myEmail: "tahyo27@gmail.com"

